// topo
export const SUCCESS_SET_TOPOICONDATA = 'SUCCESS_SET_TOPOICONDATA'
export const SUCCESS_SET_CURMAPELE = 'SUCCESS_SET_CURMAPELE'
export const SUCCESS_SET_USERICONS = 'SUCCESS_SET_USERICONS'
export const SUCCESS_SET_SYSICONS = 'SUCCESS_SET_SYSICONS'
export const SUCCESS_SET_EXCHANGER_INTERFACE_DATA = 'SUCCESS_SET_EXCHANGER_INTERFACE_DATA'
export const SUCCESS_SET_EXCHANGER_HOST_DATA = 'SUCCESS_SET_EXCHANGER_HOST_DATA'
